---
apiVersion: v1
kind: Pod
metadata:
  name: zookeeper-mysql
  labels:
    app: zksql
spec:
  hostname: zksql
  subdomain: zksqlsrv
  containers:
  - name: zookeeper
    image: <loginServerName>/zookeeper # You'll find the loginServerName at the end of this document as you follow along
    ports:
    - name: zkmain
      containerPort: 2181
      protocol: TCP
    volumeMounts:
    - mountPath: /data
      name: zk-data
    - mountPath: /datalog
      name: zk-datalog
  - name: mysql
    image: <loginServerName>/mysql # You'll find the loginServerName at the end of this document as you follow along
    ports:
    - name: sqlmain
      containerPort: 3306
      protocol: TCP
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
    env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: "true"
    - name: MYSQL_DATABASE
      value: "skil_migrations"
  volumes:
  - name: zk-data
    emptyDir: {}
  - name: zk-datalog
    emptyDir: {}
  - name: mysql-data
    emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zksqlsrv
spec:
  ports:
  - port: 2181
    targetPort: 2181
    protocol: TCP
    name: zkmain
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: sqlmain
  selector:
    app: zksql
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: skil
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: skil
    spec:
      containers:
      - name: skil
        image: <loginServerName>/skymind/skil # You'll find the loginServerName at the end of this document as you follow along
        ports:
        - name: skilmain
          containerPort: 9008
          protocol: TCP
        - name: skilzep
          containerPort: 8080
          protocol: TCP
        env:
        - name: SKIL_USE_EMBEDDED_DB
          value: "false"
        - name: SKIL_DB_NAME
          value: "skil_migrations"
        - name: SKIL_DB_DRIVER
          value: "com.mysql.jdbc.Driver"  
        - name: SKIL_DB_URL
          value: "jdbc:mysql://zksql.zksqlsrv.default.svc.cluster.local:3306/skil_migrations"  
        - name: SKIL_DB_USER
          value: "root"
        - name: MODEL_HISTORY_SERVER_LAUNCH_DEFAULT
          value: "false"  
        - name: ZEPPELIN_LAUNCH_DEFAULT
          value: "false"  
        - name: ZOOKEEPER_HOST
          value: "zksql.zksqlsrv.default.svc.cluster.local"
        - name: ZOOKEEPER_PORT
          value: "2181"
        - name: ZOOKEEPER_EMBEDDED
          value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: skil
spec:
  type: LoadBalancer
  ports:
  - port: 9008
    targetPort: 9008
    protocol: TCP
    name: skilmain
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: skilzep
  selector:
    app: skil